export const ConfigKeys = {
  AUTH: 'AUTH',
  SELECTED_REPOS: 'SELECTED_REPOS',
  LABEL_WHITELIST: 'LABEL_WHITELIST',
  LABEL_BLACKLIST: 'LABEL_BLACKLIST',
  LABEL_FILTER_ENABLED: 'LABEL_FILTER_ENABLED',
  LABEL_FILTER_MODE: 'LABEL_FILTER_MODE',
  DARK_MODE: 'DARK_MODE',
  REPO_PICKER_OPEN: 'REPO_PICKER_OPEN',
};
