export const ConfigKeys = {
  AUTH: 'AUTH',
  SELECTED_REPOS: 'SELECTED_REPOS',
  LABEL_WHITELIST: 'LABEL_WHITELIST',
  LABEL_BLACKLIST: 'LABEL_BLACKLIST',
  LABEL_FILTER_ENABLED: 'LABEL_FILTER_ENABLED',
  LABEL_FILTER_MODE: 'LABEL_FILTER_MODE',
  DARK_MODE: 'DARK_MODE',
  REPO_PICKER_OPEN: 'REPO_PICKER_OPEN',
  SHOW_DRAFTS: 'SHOW_DRAFTS',
  DRAFT_MODE: 'DRAFT_MODE',
  DRAFTS_WHITELISTED: 'DRAFTS_WHITELISTED',
  DRAFTS_BLACKLISTED: 'DRAFTS_BLACKLISTED',
};
